title:            Pablo Fabregat
tagline:          Yeah, well...
description:      Code, technical stuff and random things that no one cares
#url: http://www.pablofabregat.com

# Owner/author information
owner:
  name:           Pablo Fabregat
  avatar:         bio-photo.jpg
  bio:            "Some day I will write a random description here."
  email:          pablo.fabregat@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        p4bl3
  facebook:       
  github:         
  linkedin:       
  instagram:      
  lastfm:         
  tumblr:         
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
  - title: Setup
    url: /theme-setup/
  - title: T-Details
    url: /technical-details/
  - title: Pablo Fabregat
    url: http://www.pablofabregat.com/
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter:  true
markdown:    kramdown
permalink: pretty

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
